### ISSUE TITLE
Psych::DisallowedClass: Tried to load unspecified class: SnakyHash::StringKeyed

### ISSUE THREAD

**Issue by seriush** [beam/redmine-email-oauth#1]
Hi Andrew. I got this error at the last step
Maybe I need to update Ruby or somethinh like that?
Thanks in advance.
`** Execute redmine:email:receive_imap_oauth2
rake aborted!
Psych::DisallowedClass: Tried to load unspecified class: SnakyHash::StringKeyed
/usr/local/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find'
/usr/local/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
/usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
/usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:288:in `visit_Psych_Nodes_Mapping'
/usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
/usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/local/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
/usr/local/lib/ruby/3.1.0/psych.rb:370:in `load'
/usr/local/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
/usr/local/lib/ruby/3.1.0/psych.rb:670:in `open'
/usr/local/lib/ruby/3.1.0/psych.rb:670:in `load_file'
/usr/src/redmine/lib/tasks/email_oauth.rake:84:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:25:in `load'
/usr/local/bin/rake:25:in `<main>'
Tasks: TOP => redmine:email:receive_imap_oauth2
root@147afe5697d7:/usr/src/redmine# ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
`

**Comment by seriush** [comment]
I added these strings to the yaml module. The problem is disappeared. In my case this file is here `/usr/local/lib/ruby/3.1.0/yaml.rb`

`
module YAML
  class << self
    alias_method :load, :unsafe_load if YAML.respond_to? :unsafe_load
  end
end
`

**Comment by seriush** [comment]
It's solved.

**Comment by GamerClassN7** [comment]
I am facing the same isssue after some thinkering i found your coment i get this error after apliing your changes 
![image](https://github.com/beam/redmine-email-oauth/assets/22167469/c5c38688-b033-44af-96f9-404bc0eaed0c)
could you help me resolvethe issue.
