### ISSUE TITLE
 Rake Aborted  Error  Net::IMAP::Error: connection closed

### ISSUE THREAD

**Issue by Azrodt** [beam/redmine-email-oauth#3]
Invoke redmine:email:receive_imap_oauth2 (first_time)
** Invoke environment (first_time)
** Execute environment
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/ruby-openid-2.9.2/lib/openid/extensions/oauth.rb:10: warning: already initialized constant OpenID::OAuth::NS_URI
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/oauth.rb:10: warning: previous definition of NS_URI was here
** Execute redmine:email:receive_imap_oauth2
rake aborted!
Net::IMAP::Error: connection closed
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/net/imap.rb:1111:in `initialize'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/redmine/imap.rb:33:in `new'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/redmine/imap.rb:33:in `check'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/tasks/email_oauth.rake:105:in `block (4 levels) in <top (required)>'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/app/models/mailer.rb:630:in `with_synched_deliveries'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/tasks/email_oauth.rake:104:in `block (3 levels) in <top (required)>'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'

**Comment by Azrodt** [comment]
When i execute the code i have this error someone can help me

**Comment by Azrodt** [comment]
I use outlouk for my mailbox but when i execute always he say me connection TimeOut TCP. My port are open

**Comment by Azrodt** [comment]
Caused by:
Errno::ETIMEDOUT: Une tentative de connexion a ÚchouÚ car le parti connectÚ nÆa pas rÚpondu convenablement au-delÓ dÆune certaine durÚe ou une connexion Útablie a ÚchouÚ car lÆh¶te de connexion nÆa pas rÚpondu. - user specified timeout
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/socket.rb:61:in `connect_internal'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/socket.rb:137:in `connect'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/socket.rb:641:in `block in tcp'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/socket.rb:227:in `each'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/socket.rb:227:in `foreach'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/socket.rb:631:in `tcp'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/net/imap.rb:1132:in `tcp_socket'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/net/imap.rb:1089:in `initialize'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/redmine/imap.rb:33:in `new'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/redmine/imap.rb:33:in `check'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/tasks/email_oauth.rake:105:in `block (4 levels) in <top (required)>'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/app/models/mailer.rb:630:in `with_synched_deliveries'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/lib/tasks/email_oauth.rake:104:in `block (3 levels) in <top (required)>'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Bitnami/redmine/redmine-4.1.1-2/ruby/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
C:/Bitnami/redmine/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<main>'
Tasks: TOP => redmine:email:receive_imap_oauth2

**Comment by Azrodt** [comment]
I have also resolve this error without modification at imap.rb

**Comment by Azrodt** [comment]
Maybe i have solved my issues so what is the configuration of your  email_token.yml.

Thanks.

**Comment by ondrejbima** [comment]
You don't need edit .yml file at all, it is autogenerated by rake tasks
