### ISSUE TITLE
Issue  after redirect and pasting url pack to comand line

### ISSUE THREAD

**Issue by GamerClassN7** [beam/redmine-email-oauth#7]
Iw done everithing i could without luck 
![image](https://github.com/beam/redmine-email-oauth/assets/22167469/f81551c8-a015-46c0-a111-8a1c23e6dce5)

but i am able to create acces tocen with curl  with slightly difrent url
`
eval MSTOKEN=$(curl -X POST -H 'Content-type: application/x-www-form-urlencoded' -d "client_id=CLIENTID&scope=https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/User.Read&grant_type=password&username=redmine@itego.cz&password=PASW&client_secret=SECRET" https://login.microsoftonline.com/itego.cz/oauth2/v2.0/token | jq '.access_token')
`

Could you please advise me what i am dooing so wrong ?

**Comment by GamerClassN7** [comment]
After some time i noticed that you should not aply secret then i get auth ok but now i get this error 
![image](https://github.com/beam/redmine-email-oauth/assets/22167469/00190dbe-0eff-4541-9880-efa8837cd5fc)
with fetch command it seems like some dependency clas is missing ?

**Comment by melish** [comment]
@GamerClassN7 Try changing in email_oauth.rake:
```
      token_data = YAML.safe_load(
        File.read("#{token_file}.yml"),
        permitted_classes:[SnakyHash::StringKeyed]
      )
      access_token = OAuth2::AccessToken.from_hash(client, token_data)
```

instead of
```
access_token = OAuth2::AccessToken.from_hash(client, YAML.load_file("#{token_file}.yml"))
```

**Comment by GamerClassN7** [comment]
> @GamerClassN7 Try changing in email_oauth.rake:
> ```
>       token_data = YAML.safe_load(
>         File.read("#{token_file}.yml"),
>         permitted_classes:[SnakyHash::StringKeyed]
>       )
>       access_token = OAuth2::AccessToken.from_hash(client, token_data)
> ```
> 
> instead of
> ```
> access_token = OAuth2::AccessToken.from_hash(client, YAML.load_file("#{token_file}.yml"))
> ```
Hello 👋 @melish , thank you for your suggestions but I already created my own solution mor platform/redmine version independent, which is using modern MS graph API and Redmine native mail connector. 

https://github.com/steelants/Redmine-O365

You van check it if you want

**Comment by melish** [comment]
> Hello 👋 @melish , thank you for your suggestions but I already created my own solution mor platform/redmine version independent, which is using modern MS graph API and Redmine native mail connector.
> 
> https://github.com/steelants/Redmine-O365
> 
> You van check it if you want

Thanks, I've already  seen your repo linked from the [OAUTH redmine issue](https://www.redmine.org/issues/37688). It looks nice, I will try it.
